baseURL = "https://hntdat0805.github.io/MyBlog/"
languageCode = "vi"
title = "Blog Java & JavaScript"
theme = 'hextra'
buildDrafts = true

[params]
  navbar_title = "Java & JS Journey"
  author = "Há»“ Nguyá»…n Táº¥n Äáº¡t"
  description = "Chia sáº» kiáº¿n thá»©c vÃ  kinh nghiá»‡m láº­p trÃ¬nh Java & JavaScript"
  mainSections = ["posts"]
  show_reading_time = true
  show_toc = true
  show_share_buttons = true
  date_format = "02-01-2006"
  enable = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "ğŸ  Trang chá»§"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "ğŸ‘¨â€ğŸ’» Giá»›i thiá»‡u"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "posts"
    name = "ğŸ“° Blog"
    url = "/posts/"
    weight = 3
